services:
  - type: web
    name: hmcts-task-app
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    env: node
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: hmcts-task-app-db
          property: connectionString
      - key: NODE_ENV
        value: production
    plan: free

databases:
  - name: hmcts-task-app-db
    plan: free
    databaseName: hmcts_db
    user: hmcts_db_user